# Generated by Django 4.0.3 on 2022-03-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persons',
        ),
    ]
