# Generated by Django 4.0.3 on 2022-03-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_manager', '0002_rename_person_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databases',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
