# Generated by Django 3.1.5 on 2022-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_manager', '0003_remove_databases_owner_delete_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
